### ISSUE TITLE
I don't understand the merges of branch 2023lambert3

### ISSUE THREAD

**Issue by flipoyo** [flipoyo/MOLONARI1D#12]
est-ce que l'on pourrait en discuter car je pense qu'une partie des bugs SQL viennent de cette branche qui avait était mergée de manière pirate via Thune (avec des copier coller dans ces sources).

**Comment by fabien-ors** [comment]
La structure de la base de données dans la branche main a très peu évolué en 2023 :
https://github.com/flipoyo/MOLONARI1D/commits/main/Molonaviz/src/molonaviz/docs/ERD_structure.sql

Les modifications de la structure de la BDD présentes dans la branche 2023lambert3 depuis le 6 novembre
https://github.com/flipoyo/MOLONARI1D/commits/2023lambert3/Molonaviz/src/molonaviz/docs/ERD_structure.sql
(création de la table InputMCMC par exemple)
... n'ont jamais été mergées.

La code proposé dans SPointCoordinator.py (méthode get_table_model par exemple):
https://github.com/flipoyo/MOLONARI1D/compare/main...2023lambert3#diff-0fdaa0151bdd614617f1b165326e1318ac6132ba30e733252275115f881541ab
est visiblement obsolète quand on voit la tête de la même méthode dans la branche main:
https://github.com/flipoyo/MOLONARI1D/blob/main/Molonaviz/src/molonaviz/backend/SPointCoordinator.py

**Comment by fabien-ors** [comment]
@flipoyo veut-on conserver les démos dans cette branche : https://github.com/flipoyo/MOLONARI1D/tree/2023lambert3/Demo ?
