### ISSUE TITLE
Pb with demoInversion.ipynb

### ISSUE THREAD

**Issue by flipoyo** [flipoyo/MOLONARI1D#154]
PR#150 closed too quickly

**Comment by flipoyo** [comment]
i debugged the main. The two last cells of demoInversion.ipynb do not work. It is the link with demo_genData.ipynb
@bonbonblond please correct

**Comment by bonbonblond** [comment]
Bonjour Monsieur,

J’étais en semaine ATHENS la semaine dernière et n’ai donc pas vu vos messages. J’ai regardé, et les erreurs étaient du à des merges faits après notre pull request dans la branche principale. Ce genre de problèmes pourrait être évité en mettant demoInversion dans les conditions de code à valider pendant les pull request, car sinon les nouveaux changements ne sont pas intégrés à demoInversion.
J’ai adapté les parties du code qui avaient changé, mais il reste un problème : la fonction de Column « get_best_params » ne fonctionne plus (sa sortie est juste None). J’ai mis en commentaire la ligne de code qui comparait les paramètres réels et ceux estimés, les graphiques au dessus permettant déjà de voir si l’inversion fonctionne. En effet, je n’ai pas travaillé sur get_best_params donc je ne sais pas pourquoi la fonction ne fonctionne plus.
J’ai fait un pull request.

Bonne journée,

Ombline

Le 18 nov. 2024 à 17:35, Nicolas Flipo ***@***.***> a écrit :



i debugged the main. The two last cells of demoInversion.ipynb do not work. It is the link with demo_genData.ipynb
@bonbonblond<https://github.com/bonbonblond> please correct
