### ISSUE TITLE
MOLONAVIZ : display parameters used for the simulation

### ISSUE THREAD

**Issue by flipoyo** [flipoyo/MOLONARI1D#18]
Introduce a window where the parameters used for the simulations are displayed. It is needed for direct simulation and the best parameters of MCMC

For now:

After a mono-layer forward model, only the default parameter values are displayed in the compute window
After a multi-layer forrward model permeability is not displayed properly. Using 4 layers, the two intermediate ones display None for the parameter values
There is nowhere to view the best MCMC results (parameters that correspond to quantile 0). I am surprise because the MolonaviZ team showed me this facility once.
After a mono-layer MCMC, only the default parameter values are displayed in the compute window
After a multi-layer MCMC, same issue than for a multi-layer forward model

**Comment by fabien-ors** [comment]
Issue refactoring :
- "Display last parameters used" is duplicated with issue #35 (request removed from this issue)
Here, we only focus on the "Compute window" bugs
