### ISSUE TITLE
Display the last parameters used when showing the Compute dialog

### ISSUE THREAD

**Issue by fabien-ors** [flipoyo/MOLONARI1D#35]
When re-opening the "Compute" dialog, the parameters used the last time the dialog was open should be displayed.

**Direct Model** (top part of the window):

We feel that something is coded but it doesn't work.
- In mono layer context, factory settings parameters are used
- In multi layer context, 'None' values are displayed in first layers (see below).
![image](https://github.com/user-attachments/assets/78669454-40da-4510-ae8b-c44e79e68df2)

The "last parameters" per layer (of the last direct model run) are stored in the database (in the `Parameters` table).

Note: Best parameters per layer (obtained by the last inversion) are also stored in the database.

**Inversion** (bottom part of the window):

Factory settings are displayed.
We should create an InputMCMC table and use it as it is suggested here:
https://github.com/flipoyo/MOLONARI1D/blob/main/Molonaviz/src/molonaviz/docs/SQL_map.png

**Comment by flipoyo** [comment]
use the column class method col.get_best_layers() to get the best MCMC parameters
then rerun compute_solve_transi()

example in demoPyheatmy.ipynb
bestLayers = col.get_best_layers()
col.compute_solve_transi(bestLayers, nb_cells=100,verbose=False)

**Comment by fabien-ors** [comment]
> use the column class method col.get_best_layers() to get the best MCMC parameters then rerun compute_solve_transi()
> 
> example in demoPyheatmy.ipynb bestLayers = col.get_best_layers() col.compute_solve_transi(bestLayers, nb_cells=100,verbose=False)

This is already done at the end of save_MCMC_results in Compute.py
