### ISSUE TITLE
Impossible to import Virtual lab in MOLONAVIZ

### ISSUE THREAD

**Issue by flipoyo** [flipoyo/MOLONARI1D#50]
I create a virtual Lab and Sampling Point in $HOME/OUTPUT_MOLONARI1D/generated_files with the ipynb demo_genData.ipynb

I add in VirtualPoint the notice.txt and .jpg and .png from data/Point035 

Then I start molonaviz, create a new DB, import the virtual Lab, create a new study. 

I then import the Virtual Sampling Point but no point charges in the point area of molonaviz

The only major difference is in Pvirtual where I put intercept to 0, as well as the derivatives (maybe there is a division by zero somewhere ?

**Comment by flipoyo** [comment]
very urgent, I want to do a demo wednesday morning. I am in Fontainebleau tomorrow october 4th to discuss the issue
Thx

**Comment by fabien-ors** [comment]
I obtain a date conversion issue:
ValueError: Cannot convert dates: No known formats match your data!

The format "01/08/11 12:00:00 AM" in pressure measure files is not known by the function convertDates in general.py.
This should corresponds to "%d/%m/%y %I:%M:%S %p". It is not in the list of known formats.

But adding this format to the list dose not permits to fix the bug.
I continue to investigate

**Comment by fabien-ors** [comment]
Possible workaround: Modify your generator to use the same format than Point35:
"%m/%d/%y %I:%M:%S %p"

**Comment by flipoyo** [comment]
I found the conversion of voltage into pressure in dialogsCleanup.py:
    def convertVoltagePressure(self):
        """
        Convert the Voltage column into a (differential) Pressure field, taking into account the calibration information.
        This should only be called once, as we'd rather have the user speak in terms of differential pressure than in Voltage.
        """
        self.data["Pressure"] = (
            self.data["Voltage"] - self.data["TempBed"] * self.dUdT - self.intercept
        ) / self.dUdH
        self.data.drop(labels="Voltage", axis=1, inplace=True)

So the values in Ptest are correct and permits to state H = U cause intercept = 0, DuDt = 0 and DuDh=1
This is not the origin of the problem

**Comment by flipoyo** [comment]
Your workaround works, i close the issue.
