### ISSUE TITLE
adding the functionnality to test the 1D flow hypothesis

### ISSUE THREAD

**Issue by flipoyo** [flipoyo/MOLONARI1D#55]
Use Munz paper to check the 1D hypothesis. It will be necessary to add FFT and polygon adjustement

**Comment by flipoyo** [comment]
[munz2016_JH_1DFlux.pdf](https://github.com/user-attachments/files/17343003/munz2016_JH_1DFlux.pdf)

**Comment by alexandrenoel20** [comment]
methods added to time_series_multiperiodic class, plotting Pearson coef to test whether 1D hypothesis is relevant. Needs to add a clear function (hence a clear criteria) that returns whether 1D hypothesis is relevant or not for a dataset. Issue seems closed to me
