### ISSUE TITLE
clean up the mcmc method in core.py

### ISSUE THREAD

**Issue by flipoyo** [flipoyo/MOLONARI1D#73]
Merge the mcmc method in core.py, especially with or without sigma. The replication of multiple instructions in different methods is not acceptable.

One way to do is to set sigma2=None when not required (ie by default and add a if sigma2 != None for specificities related to sigma2

**Comment by flipoyo** [comment]
please pay attention to issue #90

**Comment by flipoyo** [comment]
reprogram compute_mcmc  merging the 3 methods compute_dream_mcmc_without_sigma2, compute_mcmc_with_sigma2, compute_mcmc_without_sigma2. 
The two last ones are a specific case of the first one.
The new method should be able to handle multiple MCMC. First, there is a burning phase for each chain. Then each iteration is divided into:
1 perturbation of the param sample
2  forward modelling
3 energy calculation
4. acceptance of the proposal
5. initialization of the prior for next step
6. storage of the forward models according to subsampling (iteration subsampling)

Once finished the last step is the quantile calculation

Please note that for the burning phase the perturbation is a classic random walk i think not using the DREAM perturbation, to be validated by thomas romary

**Comment by tromary** [comment]
Actually, the dream perturbation is performed from the beginning. It helps entering faster the stationary regime, hence reducing the burn-in phase.
