### ISSUE TITLE
Create a function to directly convert duration to seconds 

### ISSUE THREAD

**Issue by alexandrenoel20** [flipoyo/MOLONARI1D#87]
Create a function for duration/period in years, months, hours and days to be converted in seconds

**Comment by flipoyo** [comment]
OK put it in time series but see config.py before, especially the global variable in capital NSECINDAY, etc...

**Comment by alexandrenoel20** [comment]
closed with merging 2024-87-convert-to-second to main (not sure of the name of the branch but something like this)
